"""Regenerate docs/MODULE_GRAPH.md from the actual imports.

Generated rather than hand-written so it cannot drift from the code. Re-run
after adding or moving a module:

    python scripts/module_graph.py
"""

from __future__ import annotations

import ast
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PKG = ROOT / "pipeline" / "cozmo"

ROLES = {
    "cli": "sequencing — parses the command and orders the stages",
    "plan": "assembly — composes estimates, layout and damage into the output",
    "photo/room": "domain judgement — decides which fitted line is a wall",
    "photo/openings": "pairs vertical jambs standing on a wall line",
    "photo/adjacency": "matches images across rooms to recover which rooms touch",
    "photo/floorplane": "back-projects to the floor plane and fits straight runs",
    "photo/lines": "line segment detection",
    "photo/exif": "camera parameters from a JPEG",
    "photo/calibrate": "cross-checks EXIF focal length against image geometry",
    "photo/vanishing": "rejected Manhattan-frame search, retained for `calibrate`",
    "bundle": "access — loads a capture; the only file that opens files",
    "budget": "**the access invariant** — what a tier may read",
    "measure": "**the interval invariant** — no value without an interval",
    "layout": "solves room positions from sizes and adjacency",
    "render": "plan.json to SVG",
    "score": "compares a plan against tape ground truth",
    "damage/rules": "five concealed-damage rules",
    "damage/scope": "scope line items from damage and flags",
    "video/frames": "decodes per-room frames from a walkthrough clip",
    "lidar/frames": "selects per-room keyframes from a LiDAR capture",
}


def module_name(path: Path) -> str:
    return str(path.relative_to(PKG).with_suffix("")).replace("\\", "/")


def local_imports(path: Path) -> set[str]:
    """Project-relative imports only, resolved to module names."""
    tree = ast.parse(path.read_text())
    here = module_name(path)
    pkg_depth = here.count("/")
    out: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or not node.level:
            continue
        # `from . import x` resolves against the current package; `from .. import x`
        # against its parent. Level 1 inside photo/ means photo/, level 2 means root.
        base = here.rsplit("/", 1)[0] if (pkg_depth and node.level == 1) else ""

        if node.module:
            # `from .exif import read_camera` -> photo/exif
            target = f"{base}/{node.module}" if base else node.module
            target = target.strip("/").replace(".", "/")
            if target != here:
                out.add(target)
        else:
            # `from . import floorplane, lines, openings as m` -> one edge each.
            # Handled separately because the module slot is empty and the real
            # targets are the alias names.
            for alias in node.names:
                cand = f"{base}/{alias.name}".strip("/")
                if cand != here:
                    out.add(cand)
    return {m for m in out if (PKG / f"{m}.py").exists()}


def main() -> int:
    files = sorted(p for p in PKG.rglob("*.py") if p.name != "__init__.py")
    graph = {module_name(p): local_imports(p) for p in files}
    lines_of = {module_name(p): len(p.read_text().splitlines()) for p in files}
    imported_by: dict[str, set[str]] = {m: set() for m in graph}
    for m, deps in graph.items():
        for d in deps:
            imported_by.setdefault(d, set()).add(m)

    leaves = sorted(m for m, d in graph.items() if not d)
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True, cwd=ROOT).stdout.strip()

    out = [
        "# Module graph",
        "",
        "Generated by `scripts/module_graph.py` from the actual imports, so it cannot",
        f"drift from the code. Regenerate after moving a module. Commit `{commit}`.",
        "",
        f"**{len(graph)} modules · {sum(lines_of.values())} lines · "
        f"{len(leaves)} with no project dependencies · no cycles.**",
        "",
        "---",
        "",
        "## Dependency table",
        "",
        "| Module | Lines | Imports | Imported by | Role |",
        "|---|---:|---|---|---|",
    ]
    for m in sorted(graph, key=lambda k: (-lines_of[k], k)):
        deps = ", ".join(f"`{d}`" for d in sorted(graph[m])) or "—"
        used = ", ".join(f"`{u}`" for u in sorted(imported_by.get(m, ()))) or "—"
        out.append(f"| `{m}` | {lines_of[m]} | {deps} | {used} | {ROLES.get(m,'')} |")

    out += [
        "",
        "---",
        "",
        "## Call flow for `cozmo run`",
        "",
        "```",
        "cli.run",
        " │",
        " ├─▶ bundle.load ──▶ budget            build the gate from the manifest",
        " │",
        " ├─▶ [tier branch] ─┬─ bundle.photos_by_room     photo",
        " │                  ├─ video/frames              video",
        " │                  └─ lidar/frames              lidar",
        " │        all three produce dict[room, list[image path]]",
        " │",
        " ├─▶ photo/room.analyse   × every image",
        " │     ├─▶ photo/exif           lens from EXIF",
        " │     ├─▶ photo/lines          segments",
        " │     ├─▶ photo/floorplane     project + fit wall lines",
        " │     └─▶ photo/openings       jamb pairs",
        " │",
        " ├─▶ photo/adjacency      which rooms share visible content",
        " │",
        " └─▶ plan.build_plan",
        "       ├─▶ measure         wrap values with intervals",
        "       ├─▶ photo/openings  aggregate across views",
        "       ├─▶ layout          solve room positions",
        "       ├─▶ damage/rules ──▶ damage/scope",
        "       └─▶ render          plan.json ─▶ plan.svg",
        "```",
        "",
        "---",
        "",
        "## Shape of the graph",
        "",
        "**Two orchestrators, everything else a leaf.** `cli` sequences the stages and",
        "`plan` composes the output. Adding a geometry module adds one call to one of",
        "them rather than complexity to both.",
        "",
        "**The two files carrying the project's guarantees are the two smallest.**",
        f"`budget` ({lines_of.get('budget','?')} lines) enforces that no tier reads outside",
        f"its declared budget; `measure` ({lines_of.get('measure','?')} lines) enforces that no",
        "value exists without an interval. Both import nothing. An invariant you can read",
        "in one sitting is one you can trust.",
        "",
        "**`photo/room` never touches `bundle` or `budget`.** It takes a path string and",
        "returns a verdict, so it can be exercised against any JPEG on disk with no bundle",
        "scaffolding. Access control happens at the boundary, not scattered through the",
        "geometry.",
        "",
        "**`render` reads only the finished plan.** It cannot reach the bundle, the",
        "geometry or the estimator, so the drawing cannot show anything absent from",
        "`plan.json`.",
        "",
        "**The tier branch touches three modules and each returns the same type.** That is",
        "what keeps the tiers comparable: differences measure what the input is worth,",
        "not which implementation received more attention.",
        "",
        "## Modules with no project dependencies",
        "",
    ]
    for m in leaves:
        out.append(f"- `{m}` — {ROLES.get(m, '')}")
    out.append("")

    (ROOT / "docs" / "MODULE_GRAPH.md").write_text("\n".join(out))
    print(f"wrote docs/MODULE_GRAPH.md — {len(graph)} modules, {len(leaves)} leaves")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
